name: Build

on:
  pull_request:
  push:
  workflow_dispatch:
  
jobs:
  install:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Checkout the common API
        uses: actions/checkout@v2
        with:
          repository: arduino/ArduinoCore-API
          path: extras/ArduinoCore-API
          
      - name: Install Arduino-CLI
        uses: arduino/setup-arduino-cli@v1.1.1
        
      - name: Install the platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:mbed
          
      - name: install MbedOS
        run: |
          python3 -m pip install mbed-cli
       
      - name: Configure mbed
        run: |
          mbed config -G GCC_ARM_PATH $GITHUB_WORKSPACE/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin
      
      - name: Add arm GCC tools to the path
        run: |
          PATH=$GITHUB_WORKSPACE/.arduino15/packages/arduino/tools/arm-none-eabi-gcc/7-2017q4/bin:$PATH
      
      - name: symlink the Arduino API
        run: |
          ln -s $GITHUB_WORKSPACE/extras/ArduinoCore-API/api $GITHUB_WORKSPACE/cores/arduino/api
      
      - name: build core
        run: |
          ./mbed-os-to-arduino -c -u ARDUINO_NANO33BLE:ARDUINO_NANO33BLE
          
      - name: review build
        run: |
          ls -lR variants/ARDUINO_NANO33BLE
          
        
      
